package formatter

import (
	"encoding/json"
	"testing"
	"time"

	"github.com/capybara-translation/ccrec/internal/parser"
)

func makeRecord(typ string, role string, content string) *parser.Record {
	return &parser.Record{
		Type:      typ,
		Timestamp: time.Now(),
		Message: &parser.Message{
			Role:    role,
			Content: json.RawMessage(`"` + content + `"`),
		},
	}
}

func TestFilterRecords_KeepsUserAndAssistant(t *testing.T) {
	records := []*parser.Record{
		makeRecord("user", "user", "hello"),
		makeRecord("assistant", "assistant", "hi there"),
	}
	filtered := FilterRecords(records)
	if len(filtered) != 2 {
		t.Fatalf("got %d, want 2", len(filtered))
	}
}

func TestFilterRecords_ExcludesNonMessageTypes(t *testing.T) {
	records := []*parser.Record{
		makeRecord("user", "user", "hello"),
		makeRecord("file-history-snapshot", "", ""),
		makeRecord("progress", "", ""),
		makeRecord("system", "", "some system info"),
		makeRecord("summary", "", "summary text"),
	}
	filtered := FilterRecords(records)
	if len(filtered) != 1 {
		t.Fatalf("got %d, want 1 (only user message)", len(filtered))
	}
}

func TestFilterRecords_ExcludesEmptyContent(t *testing.T) {
	records := []*parser.Record{
		makeRecord("assistant", "assistant", ""),
		makeRecord("assistant", "assistant", "   "),
	}
	filtered := FilterRecords(records)
	if len(filtered) != 0 {
		t.Fatalf("got %d, want 0", len(filtered))
	}
}

func TestFilterRecords_ExcludesMetaMessages(t *testing.T) {
	rec := makeRecord("user", "user", "meta message")
	rec.IsMeta = true
	filtered := FilterRecords([]*parser.Record{rec})
	if len(filtered) != 0 {
		t.Fatalf("got %d, want 0", len(filtered))
	}
}

func TestFilterRecords_ExcludesNilMessage(t *testing.T) {
	rec := &parser.Record{Type: "user", Timestamp: time.Now()}
	filtered := FilterRecords([]*parser.Record{rec})
	if len(filtered) != 0 {
		t.Fatalf("got %d, want 0", len(filtered))
	}
}

func TestFilterRecords_ExcludesPatterns(t *testing.T) {
	tests := []struct {
		content string
	}{
		{"API Error: something went wrong"},
		{"[Request interrupted by user"},
		{"<command-name>some command</command-name>"},
		{"<bash-input>ls</bash-input>"},
		{"<local-command-stdout>output</local-command-stdout>"},
		{"Caveat: The messages below were generated by AI"},
	}

	for _, tt := range tests {
		rec := makeRecord("assistant", "assistant", tt.content)
		filtered := FilterRecords([]*parser.Record{rec})
		if len(filtered) != 0 {
			t.Errorf("content %q should be excluded, but was included", tt.content)
		}
	}
}
