package formatter

import (
	"encoding/json"
	"testing"
	"time"

	"github.com/capybara-translation/ccrec/internal/parser"
)

func makeRecord(typ string, role string, content string) *parser.Record {
	return &parser.Record{
		Type:      typ,
		Timestamp: time.Now(),
		Message: &parser.Message{
			Role:    role,
			Content: json.RawMessage(`"` + content + `"`),
		},
	}
}

func TestFilterRecords_KeepsUserAndAssistant(t *testing.T) {
	records := []*parser.Record{
		makeRecord("user", "user", "hello"),
		makeRecord("assistant", "assistant", "hi there"),
	}
	filtered := FilterRecords(records, false)
	if len(filtered) != 2 {
		t.Fatalf("got %d, want 2", len(filtered))
	}
}

func TestFilterRecords_ExcludesNonMessageTypes(t *testing.T) {
	records := []*parser.Record{
		makeRecord("user", "user", "hello"),
		makeRecord("file-history-snapshot", "", ""),
		makeRecord("progress", "", ""),
		makeRecord("system", "", "some system info"),
		makeRecord("summary", "", "summary text"),
	}
	filtered := FilterRecords(records, false)
	if len(filtered) != 1 {
		t.Fatalf("got %d, want 1 (only user message)", len(filtered))
	}
}

func TestFilterRecords_ExcludesEmptyContent(t *testing.T) {
	records := []*parser.Record{
		makeRecord("assistant", "assistant", ""),
		makeRecord("assistant", "assistant", "   "),
	}
	filtered := FilterRecords(records, false)
	if len(filtered) != 0 {
		t.Fatalf("got %d, want 0", len(filtered))
	}
}

func TestFilterRecords_ExcludesMetaMessages(t *testing.T) {
	rec := makeRecord("user", "user", "meta message")
	rec.IsMeta = true
	filtered := FilterRecords([]*parser.Record{rec}, false)
	if len(filtered) != 0 {
		t.Fatalf("got %d, want 0", len(filtered))
	}
}

func TestFilterRecords_ExcludesNilMessage(t *testing.T) {
	rec := &parser.Record{Type: "user", Timestamp: time.Now()}
	filtered := FilterRecords([]*parser.Record{rec}, false)
	if len(filtered) != 0 {
		t.Fatalf("got %d, want 0", len(filtered))
	}
}

func TestFilterRecords_ExcludesPatterns(t *testing.T) {
	tests := []struct {
		name    string
		content string
	}{
		{"API Error", "API Error: something went wrong"},
		{"Request interrupted", "[Request interrupted by user"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			rec := makeRecord("assistant", "assistant", tt.content)
			filtered := FilterRecords([]*parser.Record{rec}, false)
			if len(filtered) != 0 {
				t.Errorf("content %q should be excluded", tt.content)
			}
		})
	}
}

func TestFilterRecords_ExcludesPrefixes(t *testing.T) {
	tests := []struct {
		name    string
		content string
	}{
		{"command-name", "<command-name>some command</command-name>"},
		{"command-message", "<command-message>commit-msg-en</command-message>"},
		{"bash-input", "<bash-input>ls</bash-input>"},
		{"Caveat", "Caveat: The messages below were generated by AI"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			rec := makeRecord("user", "user", tt.content)
			filtered := FilterRecords([]*parser.Record{rec}, false)
			if len(filtered) != 0 {
				t.Errorf("content %q should be excluded by prefix", tt.content)
			}
		})
	}
}

func TestFilterRecords_PrefixInBodyDoesNotExclude(t *testing.T) {
	// <command-name> appearing inside the body (not at start) should NOT exclude the message.
	content := "Review says: <command-name>foo</command-name> is a test example"
	rec := makeRecord("user", "user", content)
	filtered := FilterRecords([]*parser.Record{rec}, false)
	if len(filtered) != 1 {
		t.Fatalf("content with prefix pattern in body should be included, got %d", len(filtered))
	}
}

func TestFilterRecords_IncludesLocalCommandStdout(t *testing.T) {
	rec := makeRecord("user", "user", "<local-command-stdout>## Review Summary\\nSome review content</local-command-stdout>")
	filtered := FilterRecords([]*parser.Record{rec}, false)
	if len(filtered) != 1 {
		t.Fatalf("local-command-stdout with content should be included, got %d", len(filtered))
	}
}

func TestFilterRecords_IncludesToolUseOnlyMessages(t *testing.T) {
	rec := &parser.Record{
		Type:      "assistant",
		Timestamp: time.Now(),
		Message: &parser.Message{
			Role:    "assistant",
			Content: json.RawMessage(`[{"type":"tool_use","name":"Read","input":{"file_path":"/tmp/test.go"}}]`),
		},
	}

	// Without includeToolUse: should be excluded (text is empty).
	filtered := FilterRecords([]*parser.Record{rec}, false)
	if len(filtered) != 0 {
		t.Fatalf("tool-only message should be excluded without includeToolUse, got %d", len(filtered))
	}

	// With includeToolUse: should be included.
	filtered = FilterRecords([]*parser.Record{rec}, true)
	if len(filtered) != 1 {
		t.Fatalf("tool-only message should be included with includeToolUse, got %d", len(filtered))
	}
}
